ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:stem: latexmath

= Getting Started

== Planning

* Checking out Datasets
** Analyzing constraints for input values
** Checking for mistakes and units
* Planning Microiterations
* Implement Software

== Datasets

=== Weather Dataset

* Temperatures are measured in Fahrenheit (stem:[\texttt{°F}])
* Constraints for temperatures:
** Minimum Temperature: stem:[\underbrace{ -90 \texttt{°C} - 10 \texttt{°C}}_{\texttt{max. temperature + offset}} \approx  -148 \texttt{°F}]
** Maximum Temperature: stem:[\underbrace{57 \texttt{°C} + 10 \texttt{°C}}_{\texttt{max. temperature + offset}} \approx  153 \texttt{°F}]

IMPORTANT: Usually, constraints such as the one for temperatures are discussed and determined *with the customer*. For the purpose of this challenge, we skip that step and determine the temperatures based on the Wikipedia page for https://de.wikipedia.org/w/index.php?title=Temperaturextrema&oldid=221928598[Temperature Extremes] and add an offset of stem:[\pm10 \texttt{°C}].


=== Football Dataset

* Goals are measured in integers
* The number of goals have to be stem:[\geq 0]

== Micro Iterations

=== Weather Challenge

We divide the challenge in following tasks:

* Model the data
* Add feature to calculated difference
* Add reader for CSV
* Add feature to identify record with smallest difference

=== Football Challenge

_ToDo_